name: "Le Slack message"
description: "Send job results on Slack via Incoming Webhooks 🔔"
inputs:
  ACTION_NAME:
    description: "Name of the action for a more descriptive message"
  JOB:
    description: "JSON-stringified `job` variable. Must be passed to output the actual status of the job"
  SLACK_WEBHOOK_URL:
    description: "URL of the Incoming Webhook provided by Slack"
runs:
  using: "node20"
  main: "index.js"
